# Generated by Django 4.2 on 2023-05-24 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseonrent',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='houseonsell',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
